// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxTj1bZS-IRMjCbBvGbqVsGZ3tnqwlAJY',
    appId: '1:900415944846:web:59c1868badb2ce309231df',
    messagingSenderId: '900415944846',
    projectId: 'smartparking-c2bdf',
    authDomain: 'smartparking-c2bdf.firebaseapp.com',
    databaseURL: 'https://smartparking-c2bdf-default-rtdb.firebaseio.com',
    storageBucket: 'smartparking-c2bdf.firebasestorage.app',
    measurementId: 'G-YCRSV31FGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_f582p7WMW-F5W0RCdimtrM8PvY9ZLfA',
    appId: '1:900415944846:android:522f0e2692c431b29231df',
    messagingSenderId: '900415944846',
    projectId: 'smartparking-c2bdf',
    databaseURL: 'https://smartparking-c2bdf-default-rtdb.firebaseio.com',
    storageBucket: 'smartparking-c2bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNledXm18J7xJ2Y6ywQwl8sGHGGtzmEU',
    appId: '1:900415944846:ios:fc016468e80196e19231df',
    messagingSenderId: '900415944846',
    projectId: 'smartparking-c2bdf',
    databaseURL: 'https://smartparking-c2bdf-default-rtdb.firebaseio.com',
    storageBucket: 'smartparking-c2bdf.firebasestorage.app',
    iosClientId: '900415944846-g8r98pnimhg0j963v0shu57avmceu7vf.apps.googleusercontent.com',
    iosBundleId: 'com.smartqueue.smartqueueAdmin',
  );
}
